controller_list:
  - name: fake_manipulator_controller
    type: $(arg execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - hande_left_finger_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: arm_zero
  - group: gripper
    pose: grip_open